### PR TITLE
Add "topic" tag for all resolvers

### PR DESCRIPTION
**Pull request by simsimler**
[It](https://github.com/kijk2869/discodo/pull/177) just reset because of [this](https://github.com/kijk2869/discodo/commit/50e73933bfe6ac7b0e1009cbf931bbbc0d1249cc)
So add "topic" tag for all resolvers and reopen the PR

### CODE REVIEW

**Comment by kijk2869** [comment]
Should fix the test codes.

**Comment by simsimler** [comment]
That means revert melon, vide resolver?

**Comment by kijk2869** [comment]
> That means revert melon, vide resolver?

This means that the test code must be modified so that the modified code can pass the Github Action.

**Comment by simsimler** [comment]
Ok

**Review by kijk2869 — APPROVED** [review]

**Pull request merged**
