### PR TITLE
feat(extractor): make our youtube extractor

### LINKED ISSUE #73: Youtube-dl is now DMCA take down.
If it will not be recovored, have to make extractor.

### PR DESCRIPTION
**Pull request by kijk2869**
will close #73

### CODE REVIEW

**Comment by kijk2869** [comment]
Assign @SaidBySolo

**Comment by SaidBySolo** [comment]
i am not member

**Review by sannoob — APPROVED** [review]
idk python but looks good

**Comment by wonderlandpark** [comment]
I like Javascript

**Comment by kijk2869** [comment]
Just use youtube mix, playlist and subtitle extractor

**Comment by kijk2869** [comment]
Test request @sannoob

**Comment by sannoob** [comment]
I'll test as fast as I can

**Comment by kijk2869** [comment]
@sannoob 

Can install with
```sh
pip install --force git+https://github.com/kijk2869/discodo.git@self-reliance```

**Pull request merged**
